version: '3'
services:
  iptv-downloader:
    # 从仓库拉取镜像（替代本地构建）
    image: https://github.dwtxaqgb.eu.org/https://github.com/dwtxaqgb1/iptv-downloader:latest
    container_name: iptv-downloader
    restart: always
    environment:
      # 保持原环境变量配置不变
      - TZ=Asia/Shanghai
      - TASK_URL=https://sub.ottiptv.cc/douyuyqk.m3u
      - FIXED_FILE_NAME=douyu.m3u
      - TASK_CRON=0 2 * * *
      - TASK_DIR=/downloads
      - OVERWRITE=true
    volumes:
      - ./files:/downloads
    network_mode: bridge
